### ISSUE TITLE
error while using login section

### ISSUE THREAD

**Issue by elseAdmin** [elseAdmin/elseFlutter#13]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'auth' was called on null.
Receiver: null
Tried calling: auth
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _UserProfileInfo.didChangeDependencies (package:else_app_two/profileTab/user_profile_info.dart:29:53)
<asynchronous suspension>
#2      StatefulElement.didChangeDependencies (package:flutter/src/widgets/framework.dart:4214:12)
#3      Element.activate (package:flutter/src/widgets/framework.dart:3205:7)
#4      StatefulElement.activate (package:flutter/src/widgets/framework.dart:4125:11)
#5      Element._activateRecursively (package:flutter/src/widgets/framework.dart:3174:13)
#6      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5216:16)
#7      Element._activateRecursively (package:flutter/src/widgets/framework.dart:3176:13)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
#9      Element._activat<…>

**Comment by elseAdmin** [comment]
Resolved
